### PR TITLE
Spec-file and scripts to build RPM

### PR DESCRIPTION
**Pull request by froller**
scripts/prepare_rpm.pl - pulls latest updates from repo, creates source tarball and updates spec-file
scripts/build_rpm.sh - builds RPM package
redhat/apmplanner2.spec - spec-file template

### CODE REVIEW

**Comment by malcom2073** [comment]
Thanks for working on this, I'll give it a shot. What operating systems are you using, Fedora?

**Comment by froller** [comment]
Yep. Fedora 20.
I'm going to test it on f21 as soon as I install one.

**Comment by malcom2073** [comment]
When I try to run it in FC21, prepare succeeds, but build does this:

https://gist.github.com/malcom2073/81816d3dfdd03edac239

Looks like somehow the tar file has clipped the first two letters of each filename.

**Comment by froller** [comment]
Yes, tar modifies filenames to make same tarballs from any directory you have cloned apm_planner

Issue
pwd > out.txt && tar -ztf ~/rpmbuild/SOURCES/apmplanner2-2.0.16.tar.gz >> out.txt
and send me an out.txt please.

Seems it's odd combination of cwd and regex leads to tarball path corruption.

**Comment by malcom2073** [comment]
Done: https://gist.github.com/malcom2073/5f310ee050042d9daa7e

**Comment by froller** [comment]
Dots in relative path name were not escaped. Thus they're treated as regex macros and ".." matched any two characters instead of ".." only.

**Comment by froller** [comment]
Malcolm, could you test build scripts on f21?

**Comment by malcom2073** [comment]
Yep, seems to work on Fedora 21. If you want to rebase your changes on top of the latest master, I'll get it pulled in (merges are bad).

**Pull request closed without merging**
