### PR TITLE
Removing trailing zeros from mouseover tooltip

### PR DESCRIPTION
**Pull request by AndKe**

### CODE REVIEW

**Comment by AndKe** [comment]
sorry, I do not know how/where to implement that,nor I am sure how it works by reading the comment :)

**Comment by billbonney** [comment]
you do something like
````
QString str = QString().sprintf( "%.4g", graph->data()->value(key).value );
````
str being formatted as you would expect

**Comment by AndKe** [comment]
Thanks, I am submitting a new pull request (just because I don't have time to figure out if it's possible to "add" to the first version of the fix.)

**Comment by AndKe** [comment]
please disregard this pull request, and accept https://github.com/diydrones/apm_planner/pull/687 instead.
(In the mean time, I've learned that I could have fixed this one instead of creating a new.)

**Pull request closed without merging**
