### PR TITLE
Full Parameter View - added keyboard shortcuts

### PR DESCRIPTION
**Pull request by AndKe**

### CODE REVIEW

**Comment by billbonney** [comment]
@AndKe I work on the commits today. Note you can make it easier if you have one PR with a number of related commits. You don't need to have one PR for one commit. Thx  :+1:

**Comment by AndKe** [comment]
But that's my fast-track to becoming a serious contributor !  :)
Just kidding - I've made one commit per Plane/Rover/Copter because that seems to be the standard for ardupilot commits. I will do all-in-one next time :)

**Comment by billbonney** [comment]
fixed in
d860cc9 MissionEditor: Allow higher default/preset altitude
56d9bfb Mission Widget: Rename Get/Set to Read/Write
8fb3b2a Mission Widget: button hotkeys
f7c06d8 Flight Modes: Hotkey, and name change
15ac5ab Tuning Setup: hotkeys for ArduRover buttons
23c8f8e Tuning Setup: hotkeys for ArduPlane buttons
6934e8b Tuning Setup: hotkeys for ArduCopter buttons
6536ac0 Full Parameter View - added keyboard shortcuts

**Comment by billbonney** [comment]
@andke it's the standard to name the commit ArduPlane ArduRover etc.  but they can be in one Pull Request. So in this case for apm_planner still have the same commits. Just one one PR

**Pull request closed without merging**
