### PR TITLE
Map Widget: Add 3D+DGPS and 3D+RTK to GPS-Fix label

### PR DESCRIPTION
**Pull request by mirkix**
This PR add 3D+DGPS and 3D+RTK to the QGCMapTool.

### CODE REVIEW

**Comment by billbonney** [comment]
I'll merge this when it is accepted in APM master.

PS: Please follow the https://github.com/diydrones/apm_planner/blob/master/CONTRIBUTING.md when making a commit, thanks :+1:

**Comment by mirkix** [comment]
@billbonney 
Thanks, the APM GPS driver

**Comment by mirkix** [comment]
@billbonney 
I don't want to close this, sorry.

**Comment by mirkix** [comment]
The patch is in apm master now.

**Comment by billbonney** [comment]
it's been added with c59edadc5b24a93edcc1bef2f32777cb708385f4

**Pull request closed without merging**
