### PR TITLE
build: remove unused files and make generic file copies

### PR DESCRIPTION
**Pull request by dcarpy**
For Windows, remove unused file copies and make generic file copies for icu*.dll files.

### CODE REVIEW

**Comment by billbonney** [comment]
@dcarpy I'm sorry but i am not sure which of these changes need to me merged with the current master or msvc-wip. I did get my build working now with MSVC2012, so let me know if I should close this PR, to cherry-pick that last commit. Thx

**Comment by dcarpy** [comment]
Yes, you can close to cherry-pick the last commit.  Thanks!

**Comment by billbonney** [comment]
closed with f739b55

**Comment by billbonney** [comment]
Wow, that broke my build and I didn't notice, I had to remove f739b55 and force pushed to master... oops :-1:

**Comment by dcarpy** [comment]
Man, I should have noticed that my change was no longer needed after the previous commit to QGCSetup.pri.

**Comment by billbonney** [comment]
No worries. I should have noticed. 

Happy New Year! :+1:

**Pull request closed without merging**
