### PR TITLE
Yum repository support

### PR DESCRIPTION
**Pull request by froller**
I've added configs to support Yum repository for RedHat-based distros.
So, if anyone is pllanning on deploying APM Planner 2 this configs would help.

yum install http://www.froller.net/diydrones/noarch/diydrones-repo-1-1.noarch.rpm
yum install apmplanner2

when the update would be available:

yum update apmplanner2

### CODE REVIEW

**Comment by froller** [comment]
No GPG keys available yet.
All the packages are not signed.

**Comment by billbonney** [comment]
Is this still relevant? if so I will merge it in. Sorry for the delay.

**Comment by froller** [comment]
Err... I need to check everything once more. I almost forget of this pull request. :)

These changes needed if you are planning on creating YUM repository for APM Planner and other related projects.

**Comment by billbonney** [comment]
cherry-picked with 54fd6cd d7af33d 230b768

 https://github.com/diydrones/apm_planner/issues/729#issuecomment-116750002

**Pull request merged**
