### PR TITLE
Windows NSIS script updates

### PR DESCRIPTION
**Pull request by dcarpy**
Changes to the native Windows NSIS script to reflect updates over the past 2 years.

### CODE REVIEW

**Comment by dcarpy** [comment]
Crap, I did something wrong.  I just wanted this pull request for the Windows NSIS script changes...

**Comment by billbonney** [comment]
No worries, I'll cherry-pick the change. Does it work for MSVC2012? I also have an issue with OpenGL linking for msvc-2012 spec.

Any specifics about the build env?

**Comment by dcarpy** [comment]
It does work for MSVC2012.  I was not cross-compiling, and was using Qt 5.4.2 (msvc2012_opengl).
Looking back though, I had commented out the code for 3DMouse...had linking problems.

**Comment by dcarpy** [comment]
Hmm...I take that back, 3DMouse builds fine.  Well, now why did I have that commented out I wonder...

**Comment by billbonney** [comment]
Merged with e8665eda52f55155caea42c71b5204b0cb7d9c75 and some other commits, let me know if it's correct. Thx (see master commit log)

**Comment by billbonney** [comment]
I still have build issue with MSVC 2012 OpenGl see #838 . If you have any pointers that would be great

**Pull request closed without merging**
