### PR TITLE
Member Variable inti for AbsPositionOverView and RelPositionOverview + RollPitchIndicator.qml update

### PR DESCRIPTION
**Pull request by HarrisonHeli**
See #625 for history.

Have made the necessary changes to prevent random values being used and causing SEG Faults when connecting to a UAS.

Should have split this but, Have rewritten the RollPitchIndicator.qml to show correctly under linux and small displays - will do more work on it but is good for now.

### CODE REVIEW

**Comment by billbonney** [comment]
Thanks for the changes. You have made a mistake that you have made your pull request from your fork on master. Then instead of rebasing your changes onto upstream master, you merged them (probably you did git pull upstream master (which is a combined fetch then merge). it's better to do git pull --ff-only upstream master as this will fail if it would be a merge. it's easier to always work on a branch for each pull request you submit. 

to fix your issue of your master != upstream master you could do
git fetch upstream # doesn't merge just gets the upstream changes.
git checkout -b yourbranchname # creates a new branch with all changes currently
git checkout upstream/master # switch to upstream/master
git branch -D master # delete your copy of master #delete my fork copy of master
git checkout -b master # create a new copy to track upstream master # create a new copy of upstream/master
git push --force origin master # fixes your github copy of the repo

You then need to apply your changes that are now *yourbranchname* branch. 

I would suggest creating a new branch from master
git checkout master
git branch -b bracnhforPR

then cherry-pick each commit onto this new branchForPR
git cherry-pick c2e37e4 
git cherry-pick c2e37e4 
git cherry-pick c2e37e4

**Comment by HarrisonHeli** [comment]
Yip. You can tell I have no clue as to what I am doing with Git :) 
Anything more than the basics and I am lost. I will have a read up today to try understand how it should all work.

Thanks for you help and understanding.

**Comment by AndKe** [comment]
works great - thank you, please add to master

**Comment by billbonney** [comment]
fixed in https://github.com/diydrones/apm_planner/commit/5a763084857e1306a8b4fa43a0d87ed2aab0c48d

**Pull request closed without merging**
